import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import StepNavigation from "./components/StepNavigation";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-slate-900`}
      >
        <div className="flex gap-5 j w-[70%] mx-auto items-center">
          <StepNavigation />
          <div className="flex">{children}</div>
        </div>
      </body>
    </html>
  );
}
