import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import StepNavigation from "./components/StepNavigation";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-slate-900 mx-auto`}
      >
        <div className="w-[60%] mx-auto flex flex-col gap-5 mt-40">
          <h1 className="text-5xl font-bold text-teal-500">Share a Deal</h1>
          <p className="text-white">
            Have an amazing deal or discount tailored for developers? Let us
            know!
          </p>
          <div className="flex flex-col lg:flex-row gap-5 items-center mt-12 ">
            <div className="w-[30%]">
              {" "}
              <StepNavigation />
            </div>

            <div className="w-[40%]">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
